default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: comment_app_development

test:
  <<: *default
  database: comment_app_test

production:
  <<: *default
  database: comment_app_production
  username: comment_app
  password: <%= ENV['COMMENT_APP_DATABASE_PASSWORD'] %>
